# Site settings
title: Sam Dennon
email: sam@dennon.me
description: "An ultra-minimalist Jekyll theme inspired by Information Architects."
baseurl: "/air"
url: "http://sam.dennon.me"

# Build settings
markdown: kramdown
permalink: :title
